### ISSUE TITLE
New Card Position

### ISSUE THREAD

**Issue by safasfasfa** [simgunz/anki-addons_fast-cards-reposition#1]
I used Fast cards reposition to change the order in which some cards appear in Anki's browser. But now, every new card I create is added to the middle of the deck, instead of the end.

I want to rearrange existing cards only. I do not want to change where newly-added cards are positioned in the browser.

**Comment by simgunz** [comment]
I think this is more an Anki upstream bug, because you'll obtain the same behaviour by using the internal reposition tool.

Anki will assign the newly created cards an index (due)  that is "last created card index+1" disregarding the fact that the dues of the cards in the deck can be changed in the meanwhile.

If you have 5 cards with due 1,2,3,4,5 and you reorder them with the internal tool so that the new dues are 10 20 30 40 50, if you add a card, the due will be 6.

Can you confirm this?

Moreover I've seen that if I create a new deck, anki doesn't start counting from 1, but sometimes it uses an higher number, which is probably based on the last due of a card with the same note type.

**Comment by matthias-samwald** [comment]
I can confirm that the behaviour seems to be to give newly created cards a "last created card index+1" due. This makes adding new cards after repositioning existing cards a bit tedious.

**Comment by simgunz** [comment]
I've asked this on the Anki support page.

https://anki.tenderapp.com/discussions/ankidesktop/15349-new-cards-not-added-at-the-end-of-the-deck-if-manual-repositioning-has-been-performed

**Comment by simgunz** [comment]
I got this answer from Anki support.

"Anki caches the last due # for performance reasons. Ideally it would update it when you reposition - for now, using Tools>Check Database will update the due # based on the highest number in the collection."

I confirm that after checking the database, the due of the new cards is correct.

Anki and my addon should be patched to update lastIndex after a reposition action. I'll look into it.

**Comment by matthias-samwald** [comment]
Thanks a lot.
I am quite new to Anki and still a bit puzzled about the ordering of cards in general. I'm a professor and am entertaining the idea of Anki decks in lieu of PowerPoint presentations; going through them during a lecture. Having a nice order predefined in a deck is important for doing that. 
However, it also seems like due # is iterated globally, not per deck (after importing an external deck, the new due numbers for my own deck jumped from around 20 to around 13000, even after running Check Database)...

**Comment by simgunz** [comment]
@matthias-samwald I suggest you to report this in the anki support conversation (see link below) so we can get some answers from the Anki creator. Unfortunately Anki has some weird behaviors sometime, and one needs to get used to it until they are fixed.

https://anki.tenderapp.com/discussions/ankidesktop/15349-new-cards-not-added-at-the-end-of-the-deck-if-manual-repositioning-has-been-performed

**Comment by simgunz** [comment]
I've fixed this. If you can test it and report any misbehavior it would be great.
