### ISSUE TITLE
fast-cards-reposition suggestion

### ISSUE THREAD

**Issue by dedu6ka** [simgunz/anki-addons_fast-cards-reposition#2]
Good add-on, but 
Suggestion:  

 It would be also as  important  -- judging by the number of requests by users-- to be able 
 to reposition a New card  between Review or Learning ( Relearning ) cards.

PS. Would be helpful to see this info in  Description:  
1.   You  must install  add-on "Advanced Browser" to be able to sort on Due col. 
2.   Can NOT insert a new card btw Review or Learning ( Relearning ) cards.  

Thank you.

**Comment by simgunz** [comment]
1. I've just tried now and I don't need "Advanced Browser" to sort by Due. I've created a profile from scratch without add on, and just by clicking on the Due column I can sort by that. Can you try with a new profile?
2. I can add this to the description, but regarding the implementation I don't think it's feasible. What does it mean reposition a new card between review cards? How do you define an ordering? This will not have any impact on how the cards will be presented, because clearly the review cards will be shown in the given due date. Or do you just want a visual ordering in the browser? But in this second case it's not related to the repositioning tool which is supposed to deal with how the NEW cards will be presented to the user.

**Comment by dedu6ka** [comment]
>  I don't need "Advanced Browser" to sort by Due.  

Sorry, my mistake; it works on the Main profile.  

>  I don't think it's feasible.       to reposition a new card between review cards.  

No need to add anything to the Description.  
I thought you could perform a magic trick ... and do it. 
Please close the issue.
