### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by etorkild** [simgunz/anki-addons_fast-cards-reposition#4]
I've downloaded the add-on, restarted Anki, and while it shows up under tools, it does not open up in browse.
Using MacBook pro. If you need any other info, let me know.

It works fine on my other computer (MacBook pro).

Thanks.

**Comment by simgunz** [comment]
Have you sorted the cards by due date?

On Sat, Mar 11, 2017, 15:09 etorkild <notifications@github.com> wrote:

I've downloaded the add-on, restarted Anki, and while it shows up under
tools, it does not open up in browse.

It works fine on my other computer.

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/simgunz/anki-addons_fast-cards-reposition/issues/4>,
or mute
the thread

**Comment by etorkild** [comment]
Good call, thank you! Sorry, haha! Really useful add-on, thank you. 

Eric Torkildsen
